### ISSUE TITLE
DeltaTime/FrameCount Assert on Windows

### ISSUE THREAD

**Issue by dusk125** [inkyblackness/imgui-go#122]
Hey, I've been working on an application in Linux using OpenGL and Imgui-go that has been building and running fine. I just tried to build and run it on Windows, using MinGW), it builds fine, but I'm getting the assert below that I wasn't getting running the same thing on Linux. From the stack trace, this looks like a Dear ImGUI issue, but I wanted to start here since I'm not familiar with how imgui-go is initializing ImGUI.

Any advice is greatly appreciated.

My build command:
`go build -v -tags='imguifreetype" -tags='glfw'`

Stack Trace:
```
panic: Assertion failed!
File: C:\Users\allen\Dev\go\src\github.com\inkyblackness\imgui-go\imgui/imgui.cpp, Line 6732

Expression: (g.IO.DeltaTime > 0.0f || g.FrameCount == 0) && "Need a positive DeltaTime!"


goroutine 6 [running]:
github.com/inkyblackness/imgui-go.glob..func2(0xc000228000, 0x4c, 0xc000228050, 0x4b, 0x1a4c)
        C:/Users/allen/Dev/go/src/github.com/inkyblackness/imgui-go/Assert.go:28 +0xa2
github.com/inkyblackness/imgui-go.iggAssert(0x8a2d90, 0x89f960, 0x3fd5c28f00001a4c)
        C:/Users/allen/Dev/go/src/github.com/inkyblackness/imgui-go/Assert.go:45 +0xac
github.com/inkyblackness/imgui-go._cgoexpwrap_9cc7a7a8d41e_iggAssert(0x8a2d90, 0x89f960, 0x1a4c)
        _cgo_gotypes.go:4069 +0x44
github.com/inkyblackness/imgui-go._Cfunc_iggNewFrame()
        _cgo_gotypes.go:2999 +0x48
github.com/inkyblackness/imgui-go.NewFrame(...)
        C:/Users/allen/Dev/go/src/github.com/inkyblackness/imgui-go/Main.go:18
github.com/dusk125/pixelui.(*UI).NewFrame(0xc00025e000)
        C:/Users/allen/Dev/go/src/github.com/dusk125/pixelui/ui.go:122 +0x60
main.run()
        C:/Users/allen/Dev/go/src/github.com/dusk125/musync/musync.go:96 +0x3c2
github.com/faiface/mainthread.Run.func1(0x737018, 0xc0000540c0)
        C:/Users/allen/Dev/go/src/github.com/faiface/mainthread/mainthread.go:37 +0x2e
created by github.com/faiface/mainthread.Run
        C:/Users/allen/Dev/go/src/github.com/faiface/mainthread/mainthread.go:36 +0xb8
```

Thanks in advance!

**Comment by dertseha** [comment]
Hello there and thank you for your message.
ImGui assumes (or, it could also be written as: "expects") that `NewFrame()` is called with some time passing before the next call to `NewFrame()`. It uses this timespan to calculate... stuff. Ideally, this `IO.SetDeltaTime()` is being called with the time it took between the last call to `NewFrame()` to the next one.

I've had a look at your code in https://github.com/dusk125/pixelui/blob/master/ui.go - and it seems that the time calculation there is a little off.
1. `UI.NewFrame()` sets `ui.timer` with a new `time.Now()`
2. `UI.update()` then calls `ui.io.SetDeltaTime(float32(time.Since(ui.timer).Seconds()))`

This means, the code only measures the time between the call to `NewFrame()` to `UI.update()`. I assume this can be a very short time as they probably will be called in pairs. And, in case MS Windows is *still* providing a rough time resolution in ~15 millisecond intervals, it might resolve to a zero time.

If you look at the example code in [imgu-go-examples](https://github.com/inkyblackness/imgui-go-examples/blob/master/internal/platforms/glfw.go#L109-L113), the time is measured between each call to `NewFrame()`.

Try modifying your code this way, it should help.

**Comment by dusk125** [comment]
Ahh thank you! You're right, changing the delta to measure between UI.NewFrame calls did the trick.

Also, this project (and Dear ImGUI) are great, I had a fun time getting the render data to draw properly in the Pixel render stack.
